services:
  linkding:
    container_name: linkding
    image: sissbruecker/linkding:latest
    ports:
      - "9090:9090"
    volumes:
      - "./data:/etc/linkding/data"
    environment:
      # Nome do contêiner já definido acima, não precisa repetir
      # Configuração do superusuário inicial
      - LD_SUPERUSER_NAME=admin
      - LD_SUPERUSER_PASSWORD=sua_senha_segura
      # Opções gerais do Linkding
      - LD_CONTEXT_PATH=
      - LD_DISABLE_BACKGROUND_TASKS=False
      - LD_DISABLE_URL_VALIDATION=False
      - LD_ENABLE_AUTH_PROXY=False
      - LD_AUTH_PROXY_USERNAME_HEADER=
      - LD_AUTH_PROXY_LOGOUT_URL=
      - LD_CSRF_TRUSTED_ORIGINS=
      # Configuração do banco de dados (SQLite por padrão)
      - LD_DB_ENGINE=sqlite
      # As variáveis abaixo são opcionais para SQLite e podem ser omitidas
      # - LD_DB_DATABASE=
      # - LD_DB_USER=
      # - LD_DB_PASSWORD=
      # - LD_DB_HOST=
      # - LD_DB_PORT=
      # - LD_DB_OPTIONS=
    restart: unless-stopped
